package cz.somsi.app;

import android.app.*;import android.os.*;import android.content.*;import android.graphics.*;import android.net.Uri;import android.provider.MediaStore;import android.view.*;import android.widget.*;

public class MainActivity extends Activity{
 final int GOLD=Color.rgb(232,169,46),DARK=Color.rgb(7,13,17),PANEL=Color.rgb(20,28,33),TEXT=Color.WHITE,MUTED=Color.rgb(185,193,197); FrameLayout root; SomsiView view; android.content.SharedPreferences pref; int visits,active,done,planned;
 public void onCreate(Bundle b){super.onCreate(b);pref=getSharedPreferences("somsi",0);visits=pref.getInt("v",1248);active=pref.getInt("a",86);done=pref.getInt("d",67);planned=pref.getInt("p",12);build();}
 int dp(float x){return(int)(x*getResources().getDisplayMetrics().density+.5f);} void save(){pref.edit().putInt("v",visits).putInt("a",active).putInt("d",done).putInt("p",planned).apply();}
 void build(){root=new FrameLayout(this);view=new SomsiView(this);ScrollView s=new ScrollView(this);s.setFillViewport(true);s.addView(view,new ScrollView.LayoutParams(-1,dp(1120)));root.addView(s,new FrameLayout.LayoutParams(-1,-1));LinearLayout nav=new LinearLayout(this);nav.setGravity(Gravity.CENTER);nav.setBackgroundColor(Color.rgb(8,14,18));String[] n={"⌂\nDomů","▣\nZakázky","＋\nNový","●\nChat","☰\nMenu"};for(String z:n){TextView t=new TextView(this);t.setText(z);t.setTextColor(TEXT);t.setTextSize(11);t.setGravity(Gravity.CENTER);t.setTypeface(Typeface.DEFAULT,Typeface.BOLD);t.setOnClickListener(v->{String x=((TextView)v).getText().toString();if(x.contains("Domů"))show("Domů");else if(x.contains("Zakázky"))show("Zakázky");else if(x.contains("Chat"))show("Chat");else if(x.contains("Nový"))newRecord();else menu();});nav.addView(t,new LinearLayout.LayoutParams(0,dp(68),1));}root.addView(nav,new FrameLayout.LayoutParams(-1,dp(70),Gravity.BOTTOM));setContentView(root);}
 void show(String x){view.sec=x;view.invalidate();}
 void newRecord(){visits++;active++;save();Toast.makeText(this,"Nový záznam uložen",Toast.LENGTH_SHORT).show();view.invalidate();}
 void menu(){new AlertDialog.Builder(this).setTitle("SOMSI – Menu").setItems(new String[]{"Adresář","Fotodokumentace","Stavební deník","Úkoly","Docházka","Materiál","Dokumenty","Nastavení"},(d,w)->{if(w==1)camera();else show(new String[]{"Adresář","Fotodokumentace","Stavební deník","Úkoly","Docházka","Materiál","Dokumenty","Nastavení"}[w]);}).show();}
 void camera(){try{startActivity(new Intent(MediaStore.ACTION_IMAGE_CAPTURE));}catch(Exception e){Toast.makeText(this,"Fotoaparát není dostupný",Toast.LENGTH_SHORT).show();}}
 void call(){startActivity(new Intent(Intent.ACTION_DIAL,Uri.parse("tel:+420000000000")));}
 void chat(){EditText e=new EditText(this);e.setHint("Napište zprávu…");new AlertDialog.Builder(this).setTitle("SOMSI Chat").setView(e).setNegativeButton("Zrušit",null).setPositiveButton("Odeslat",(d,w)->{if(e.length()>0)Toast.makeText(this,"Zpráva odeslána",Toast.LENGTH_SHORT).show();}).show();}
 class SomsiView extends View{
  Paint p=new Paint(3);String sec="Domů";RectF r=new RectF();float den;
  SomsiView(Context c){super(c);den=getResources().getDisplayMetrics().density;}
  float W(){return getWidth()/den;} void text(Canvas c,String s,float x,float y,float z,int col,boolean b){p.setShader(null);p.setStyle(Paint.Style.FILL);p.setColor(col);p.setTextSize(dp(z));p.setTypeface(Typeface.create("sans",b?Typeface.BOLD:Typeface.NORMAL));c.drawText(s,dp(x),dp(y),p);} void box(Canvas c,float l,float t,float rr,float bb,int col,float rad){p.setShader(null);p.setStyle(Paint.Style.FILL);p.setColor(col);r.set(dp(l),dp(t),dp(rr),dp(bb));c.drawRoundRect(r,dp(rad),dp(rad),p);}
  protected void onDraw(Canvas c){c.drawColor(DARK);if(sec.equals("Domů"))home(c);else page(c);}
  void home(Canvas c){float w=W();p.setShader(new LinearGradient(0,0,0,dp(285),Color.rgb(9,22,29),Color.rgb(35,43,40),Shader.TileMode.CLAMP));c.drawRect(0,0,getWidth(),dp(285),p);p.setShader(null);p.setColor(Color.rgb(48,59,59));c.drawRect(dp(24),dp(150),dp(w-24),dp(270),p);Path roof=new Path();roof.moveTo(dp(15),dp(153));roof.lineTo(dp(w/2),dp(58));roof.lineTo(dp(w-8),dp(153));roof.close();p.setColor(Color.rgb(67,73,68));c.drawPath(roof,p);p.setColor(Color.rgb(23,31,34));c.drawRect(dp(52),dp(178),dp(125),dp(270),p);c.drawRect(dp(w-125),dp(178),dp(w-52),dp(270),p);p.setColor(GOLD);c.drawRect(dp(w/2-18),dp(202),dp(w/2+18),dp(270),p);p.setShader(new LinearGradient(0,0,0,dp(285),0x22000000,0xD0000000,Shader.TileMode.CLAMP));c.drawRect(0,0,getWidth(),dp(285),p);p.setShader(null);text(c,"☰",16,43,28,TEXT,false);text(c,"SOMSI",76,58,30,TEXT,true);text(c,"stavební práce",78,83,16,TEXT,false);text(c,"Od základu po střechu",69,117,18,GOLD,true);text(c,"KVALITA",w-105,54,9,MUTED,false);text(c,"ZKUŠENOSTI",w-105,75,9,MUTED,false);text(c,"SPOLEHLIVOST",w-105,96,9,MUTED,false);text(c,"Stavíme",w-112,175,18,TEXT,true);text(c,"Vaše plány",w-112,198,18,TEXT,true);text(c,"do reality",w-112,221,18,TEXT,true);stats(c);grid(c);call(c);}
  void stats(Canvas c){float gap=5,l=10,top=300,cw=(W()-20-gap*3)/4;String[] name={"Návštěvy","Zakázky","Dokončeno","Plán"};String[] val={""+visits,""+active,""+done,""+planned};for(int i=0;i<4;i++){float x=l+i*(cw+gap);box(c,x,top,x+cw,top+88,PANEL,12);text(c,val[i],x+cw/2-18,top+38,18,TEXT,true);text(c,name[i],x+cw/2-28,top+61,9,TEXT,false);if(i<2)text(c,i==0?"+12%":"+8%",x+cw/2-12,top+78,8,Color.rgb(110,225,110),true);}}
  void grid(Canvas c){String[] n={"Zakázky","Fotodokumentace","Stavební deník","Úkoly","Docházka","Materiál","Dokumenty","Adresář","Chat"};String[] ic={"▣","●","▤","✓","●","◆","▤","♟","●"};float gap=6,l=10,top=402,cw=(W()-20-gap*2)/3,ch=86;for(int i=0;i<9;i++){int row=i/3,col=i%3;float x=l+col*(cw+gap),y=top+row*(ch+gap);box(c,x,y,x+cw,y+ch,i==0?Color.rgb(164,112,26):PANEL,13);text(c,ic[i],x+10,y+31,21,i==0?TEXT:GOLD,true);text(c,n[i],x+36,y+34,11,TEXT,true);text(c,"›",x+cw-18,y+38,18,GOLD,true);if(i==8){box(c,x+cw-24,y+5,x+cw-5,y+24,Color.rgb(238,75,50),10);text(c,"3",x+cw-18,y+19,8,TEXT,true);}}}
  void call(Canvas c){float y=688,w=W();box(c,10,y,w-10,y+82,Color.rgb(17,25,29),14);text(c,"☎",23,y+47,25,GOLD,true);text(c,"Potřebujete konzultaci?",58,y+33,13,TEXT,true);text(c,"Ozvěte se nám!",58,y+55,12,MUTED,false);box(c,w-105,y+17,w-25,y+65,GOLD,10);text(c,"Zavolat",w-91,y+47,12,Color.BLACK,true);text(c,"⌖  Horní Studenec 29",18,y+115,11,MUTED,false);text(c,"Pardubický kraj · Královéhradecký kraj · Vysočina",18,y+138,10,TEXT,false);}
  void page(Canvas c){float w=W();text(c,"‹",16,43,30,GOLD,true);text(c,sec,55,40,22,TEXT,true);text(c,"SOMSI",w-70,40,16,GOLD,true);box(c,12,65,w-12,235,PANEL,16);if(sec.equals("Zakázky")){text(c,"AKTIVNÍ ZAKÁZKY",28,98,11,MUTED,true);text(c,"86",28,140,30,TEXT,true);text(c,"Novostavba – Horní Studenec",112,103,13,TEXT,true);text(c,"Fasáda a zateplení",112,129,11,MUTED,false);text(c,"Dokončení: 30. 10. 2026",112,155,10,GOLD,true);}else if(sec.equals("Adresář")){text(c,"KONTAKTY",28,98,11,MUTED,true);text(c,"Jan Novák",28,132,16,TEXT,true);text(c,"stavbyvedoucí · +420 000 000 001",28,153,10,MUTED,false);text(c,"Petr Svoboda",28,184,16,TEXT,true);text(c,"zedník · +420 000 000 002",28,205,10,MUTED,false);}else if(sec.equals("Chat")){text(c,"TEAM CHAT",28,98,11,MUTED,true);text(c,"●  Stavbyvedoucí",28,132,14,TEXT,true);text(c,"Materiál dorazí zítra v 8:00.",28,153,11,MUTED,false);text(c,"●  Petr",28,184,14,TEXT,true);text(c,"Fotky z dneška jsou nahrané.",28,205,11,MUTED,false);box(c,28,250,w-28,305,Color.rgb(33,43,48),10);text(c,"Napsat zprávu…",43,283,11,MUTED,false);}else{text(c,"PŘEHLED",28,98,11,MUTED,true);text(c,"Sekce "+sec,28,138,21,TEXT,true);text(c,"Funkce je připravena pro práci v telefonu.",28,166,11,MUTED,false);}text(c,"Klepni na ‹ pro návrat",28,350,11,MUTED,false);}
  public boolean onTouchEvent(MotionEvent e){if(e.getAction()!=MotionEvent.ACTION_UP)return true;float x=e.getX()/den,y=e.getY()/den;if(sec.equals("Domů")){if(y>=402&&y<684){int row=(int)((y-402)/92),col=(int)(x/(W()/3));int i=row*3+col;String[] n={"Zakázky","Fotodokumentace","Stavební deník","Úkoly","Docházka","Materiál","Dokumenty","Adresář","Chat"};if(i>=0&&i<9){if(i==1)camera();else if(i==8)chat();else show(n[i]);}}else if(y>=688&&y<=775&&x>W()-120)call();}else if(y<60)show("Domů");else if(sec.equals("Chat")&&y>245&&y<320)chat();return true;}
 }
}
