package cz.somsi.app;

import android.app.*;
import android.os.*;
import android.content.*;
import android.database.Cursor;
import android.database.sqlite.*;
import android.graphics.*;
import android.net.Uri;
import android.provider.MediaStore;
import android.view.*;
import android.widget.*;
import java.util.*;

public class MainActivity extends Activity {
    static final int GOLD=Color.rgb(242,174,43), GOLD2=Color.rgb(255,196,75), GOLD_DARK=Color.rgb(185,126,18);
    static final int BG=Color.rgb(5,11,15), PANEL=Color.rgb(16,24,29), PANEL2=Color.rgb(23,33,39);
    static final int WHITE=Color.WHITE, MUTED=Color.rgb(190,198,203), GREEN=Color.rgb(91,214,112), RED=Color.rgb(239,78,58);
    static final String WEB="https://stavbysomsi.cz/", PHONE="+420736771754";
    FrameLayout root; HomeView home; BottomView bottom; ScrollView scroll; DB db; Bitmap hero;
    int visits,active,done,planned; String section="Domů";
    @Override public void onCreate(Bundle b){super.onCreate(b);getWindow().setStatusBarColor(BG);getWindow().setNavigationBarColor(BG);if(Build.VERSION.SDK_INT>=29)getWindow().setNavigationBarContrastEnforced(false);if(Build.VERSION.SDK_INT>=30)getWindow().setDecorFitsSystemWindows(false);db=new DB(this);android.content.SharedPreferences p=getSharedPreferences("somsi",0);visits=p.getInt("v",1248);active=p.getInt("a",86);done=p.getInt("d",67);planned=p.getInt("p",12);hero=BitmapFactory.decodeResource(getResources(),R.drawable.realizace_hlavni);build();}
    int dp(float v){return (int)(v*getResources().getDisplayMetrics().density+.5f);} float den(){return getResources().getDisplayMetrics().density;}
    void build(){root=new FrameLayout(this);root.setBackgroundColor(BG);home=new HomeView(this);scroll=new ScrollView(this);scroll.setFillViewport(false);scroll.setClipToPadding(false);scroll.setOverScrollMode(View.OVER_SCROLL_NEVER);scroll.setPadding(0,0,0,dp(92));scroll.addView(home,new ScrollView.LayoutParams(-1,dp(1390)));root.addView(scroll,new FrameLayout.LayoutParams(-1,-1));bottom=new BottomView(this);root.addView(bottom,new FrameLayout.LayoutParams(-1,dp(78),Gravity.BOTTOM));bottom.setOnApplyWindowInsetsListener((v,in)->{int n=0;if(Build.VERSION.SDK_INT>=30)n=in.getInsets(WindowInsets.Type.navigationBars()).bottom;else n=in.getSystemWindowInsetBottom();FrameLayout.LayoutParams lp=(FrameLayout.LayoutParams)v.getLayoutParams();lp.height=dp(78)+n;v.setLayoutParams(lp);return in;});setContentView(root);}
    void persist(){getSharedPreferences("somsi",0).edit().putInt("v",visits).putInt("a",active).putInt("d",done).putInt("p",planned).apply();}
    void openWeb(){try{startActivity(new Intent(Intent.ACTION_VIEW,Uri.parse(WEB)));}catch(Exception e){Toast.makeText(this,"Web nelze otevřít",Toast.LENGTH_SHORT).show();}}
    void call(){try{startActivity(new Intent(Intent.ACTION_DIAL,Uri.parse("tel:"+PHONE)));}catch(Exception e){Toast.makeText(this,"Telefon není dostupný",Toast.LENGTH_SHORT).show();}}
    void camera(){try{startActivity(new Intent(MediaStore.ACTION_IMAGE_CAPTURE));}catch(Exception e){Toast.makeText(this,"Fotoaparát není dostupný",Toast.LENGTH_SHORT).show();}}
    void go(String s){section=s;home.invalidate();scroll.scrollTo(0,0);}
    void newRecord(){visits++;active++;db.addRecord("Nový záznam","Vytvořen v aplikaci");persist();Toast.makeText(this,"Nový záznam uložen",Toast.LENGTH_SHORT).show();home.invalidate();}
    void showMenu(){final String[] a={"Zakázky","Fotodokumentace","Stavební deník","Úkoly","Docházka","Materiál","Dokumenty","Adresář","Otevřít web SOMSI","Zavolat SOMSI"};new AlertDialog.Builder(this).setTitle("SOMSI – Menu").setItems(a,(d,w)->{if(w==8)openWeb();else if(w==9)call();else if(w==1)camera();else go(a[w]);}).show();}
    void chat(){final EditText e=new EditText(this);e.setHint("Napište zprávu…");e.setMinLines(3);e.setGravity(Gravity.TOP);LinearLayout box=new LinearLayout(this);box.setPadding(dp(18),0,dp(18),0);box.addView(e,new LinearLayout.LayoutParams(-1,-2));new AlertDialog.Builder(this).setTitle("SOMSI Chat").setMessage("Lokální chat uložený v telefonu.").setView(box).setNegativeButton("Zrušit",null).setPositiveButton("Odeslat",(d,w)->{String m=e.getText().toString().trim();if(!m.isEmpty()){db.addMessage("Já",m);Toast.makeText(this,"Zpráva uložena",Toast.LENGTH_SHORT).show();go("Chat");}}).show();}

    class HomeView extends View{
        Paint p=new Paint(Paint.ANTI_ALIAS_FLAG|Paint.FILTER_BITMAP_FLAG);RectF r=new RectF();String[] names={"Zakázky","Fotodokumentace","Stavební deník","Úkoly","Docházka","Materiál","Dokumenty","Adresář","Chat"};
        HomeView(Context c){super(c);setLayerType(View.LAYER_TYPE_SOFTWARE,null);} float W(){return getWidth()/den();}
        void fill(Canvas c,int color,float l,float t,float rr,float bb,float rad){p.setShader(null);p.setStyle(Paint.Style.FILL);p.setColor(color);r.set(dp(l),dp(t),dp(rr),dp(bb));c.drawRoundRect(r,dp(rad),dp(rad),p);}
        void line(Canvas c,int color,float sw,float x1,float y1,float x2,float y2){p.setShader(null);p.setStyle(Paint.Style.STROKE);p.setStrokeWidth(dp(sw));p.setStrokeCap(Paint.Cap.ROUND);p.setColor(color);c.drawLine(dp(x1),dp(y1),dp(x2),dp(y2),p);p.setStyle(Paint.Style.FILL);}
        void txt(Canvas c,String s,float x,float y,float size,int color,boolean bold){p.setShader(null);p.setStyle(Paint.Style.FILL);p.setColor(color);p.setTextSize(dp(size));p.setTypeface(Typeface.create("sans",bold?Typeface.BOLD:Typeface.NORMAL));c.drawText(s,dp(x),dp(y),p);}
        void center(Canvas c,String s,float x,float y,float size,int color,boolean bold){p.setTextSize(dp(size));p.setTypeface(Typeface.create("sans",bold?Typeface.BOLD:Typeface.NORMAL));p.setColor(color);p.setStyle(Paint.Style.FILL);c.drawText(s,dp(x)-p.measureText(s)/2,dp(y),p);}
        void icon(Canvas c,float x,float y,int type,int color){p.setColor(color);p.setStyle(Paint.Style.STROKE);p.setStrokeWidth(dp(2.4f));p.setStrokeCap(Paint.Cap.ROUND);float X=dp(x),Y=dp(y);if(type==0){c.drawRect(X-dp(9),Y-dp(5),X+dp(9),Y+dp(8),p);c.drawLine(X-dp(5),Y-dp(9),X+dp(5),Y-dp(9),p);}else if(type==1){c.drawCircle(X,Y,dp(9),p);c.drawLine(X-dp(9),Y+dp(7),X+dp(9),Y+dp(7),p);}else if(type==2){c.drawRect(X-dp(8),Y-dp(10),X+dp(8),Y+dp(10),p);c.drawLine(X-dp(4),Y-dp(3),X+dp(4),Y-dp(3),p);c.drawLine(X-dp(4),Y+dp(3),X+dp(5),Y+dp(3),p);}else if(type==3){c.drawLine(X-dp(9),Y,X-dp(2),Y+dp(7),p);c.drawLine(X-dp(2),Y+dp(7),X+dp(10),Y-dp(8),p);}else if(type==4){c.drawCircle(X,Y-dp(4),dp(4),p);c.drawArc(new RectF(X-dp(10),Y+dp(1),X+dp(10),Y+dp(13)),180,180,false,p);}else if(type==5){Path q=new Path();q.moveTo(X,Y-dp(10));q.lineTo(X+dp(10),Y);q.lineTo(X,Y+dp(10));q.lineTo(X-dp(10),Y);q.close();c.drawPath(q,p);}else if(type==6){c.drawRect(X-dp(8),Y-dp(10),X+dp(8),Y+dp(10),p);c.drawLine(X-dp(5),Y-dp(3),X+dp(5),Y-dp(3),p);c.drawLine(X-dp(5),Y+dp(2),X+dp(5),Y+dp(2),p);}else if(type==7){c.drawCircle(X,Y-dp(5),dp(5),p);c.drawRoundRect(new RectF(X-dp(10),Y+dp(1),X+dp(10),Y+dp(11)),dp(4),dp(4),p);}else{c.drawOval(new RectF(X-dp(10),Y-dp(7),X+dp(10),Y+dp(7)),p);c.drawCircle(X-dp(4),Y,dp(1),p);c.drawCircle(X,Y,dp(1),p);c.drawCircle(X+dp(4),Y,dp(1),p);}p.setStyle(Paint.Style.FILL);p.setStrokeCap(Paint.Cap.BUTT);}
        void bell(Canvas c,float x,float y){p.setColor(WHITE);p.setStyle(Paint.Style.STROKE);p.setStrokeWidth(dp(2.2f));c.drawArc(new RectF(dp(x-9),dp(y-10),dp(x+9),dp(y+10)),200,140,false,p);c.drawLine(dp(x-9),dp(y+3),dp(x-9),dp(y+9),p);c.drawLine(dp(x+9),dp(y+3),dp(x+9),dp(y+9),p);c.drawLine(dp(x-12),dp(y+9),dp(x+12),dp(y+9),p);p.setStyle(Paint.Style.FILL);c.drawCircle(dp(x),dp(y+12),dp(2),p);}
        void logo(Canvas c,float cx,float top){p.setColor(GOLD);p.setStyle(Paint.Style.STROKE);p.setStrokeWidth(dp(7));p.setStrokeCap(Paint.Cap.SQUARE);Path roof=new Path();roof.moveTo(dp(cx-80),dp(top+48));roof.lineTo(dp(cx),dp(top));roof.lineTo(dp(cx+80),dp(top+48));c.drawPath(roof,p);c.drawLine(dp(cx-42),dp(top+27),dp(cx-42),dp(top+82),p);p.setStyle(Paint.Style.FILL);p.setStrokeCap(Paint.Cap.BUTT);center(c,"SOMSI",cx,top+78,39,WHITE,true);center(c,"stavební práce",cx,top+108,18,WHITE,false);center(c,"Od základu po střechu",cx,top+137,19,GOLD2,true);}
        @Override protected void onDraw(Canvas c){c.drawColor(BG);if(section.equals("Domů"))drawHome(c);else drawPage(c);}
        void drawHome(Canvas c){float w=W();if(hero!=null){float targetH=390;float sc=Math.max(getWidth()/(float)hero.getWidth(),dp(targetH)/(float)hero.getHeight());float bw=hero.getWidth()*sc,bh=hero.getHeight()*sc;c.save();c.clipRect(0,0,getWidth(),dp(targetH));c.drawBitmap(hero,null,new RectF((getWidth()-bw)/2,0,(getWidth()+bw)/2,bh),p);c.restore();p.setColor(0x30000000);c.drawRect(0,0,getWidth(),dp(targetH),p);}else{p.setColor(PANEL2);c.drawRect(0,0,getWidth(),dp(390),p);}txt(c,"☰",18,51,33,WHITE,false);bell(c,w-39,38);fill(c,RED,w-24,17,w-4,37,11);center(c,"3",w-14,32,9,WHITE,true);fill(c,0xB5050B0F,w-91,17,w-15,59,14);center(c,"WEB",w-53,45,12,GOLD2,true);logo(c,w/2,47);txt(c,"KVALITA",w-117,155,9,MUTED,true);txt(c,"ZKUŠENOSTI",w-117,177,9,MUTED,true);txt(c,"SPOLEHLIVOST",w-117,199,9,MUTED,true);txt(c,"VAŠE STAVBA",w-117,221,9,MUTED,true);txt(c,"NAŠE PRIORITA",w-117,243,9,MUTED,true);txt(c,"Stavíme",w-119,286,21,WHITE,true);txt(c,"Vaše plány",w-119,313,21,WHITE,true);txt(c,"do reality",w-119,340,21,WHITE,true);line(c,GOLD,2,w-119,354,w-28,354);stats(c);tiles(c);callPanel(c);webPanel(c);contact(c);}
        void stats(Canvas c){float w=W(),gap=7,l=10,top=407,cw=(w-20-gap*3)/4;String[] v={""+visits,""+active,""+done,""+planned},n={"Návštěvy","Zakázky","Dokončeno","Plán"};for(int i=0;i<4;i++){float x=l+i*(cw+gap);fill(c,PANEL,x,top,x+cw,top+96,15);icon(c,x+cw/2,top+20,i==0?4:i==1?1:i==2?3:2,GOLD2);center(c,v[i],x+cw/2,top+54,18,WHITE,true);center(c,n[i],x+cw/2,top+76,8.7f,MUTED,false);if(i<2)center(c,i==0?"+12% ↗":"+8% ↗",x+cw/2,top+90,7.5f,GREEN,true);}}
        void tiles(Canvas c){float w=W(),gap=8,l=10,top=520,cw=(w-20-gap*2)/3,ch=96;for(int i=0;i<9;i++){int row=i/3,col=i%3;float x=l+col*(cw+gap),y=top+row*(ch+gap);fill(c,i==0?GOLD_DARK:PANEL,x,y,x+cw,y+ch,16);fill(c,i==0?Color.rgb(250,199,88):Color.rgb(40,54,61),x+9,y+10,x+49,y+50,12);icon(c,x+29,y+30,i,i==0?Color.BLACK:GOLD2);txt(c,names[i],x+57,y+39,10.2f,WHITE,true);txt(c,"›",x+cw-20,y+43,22,GOLD2,true);if(i==8){fill(c,RED,x+cw-31,y+7,x+cw-7,y+31,13);center(c,"3",x+cw-19,y+24,9,WHITE,true);}}}
        void callPanel(Canvas c){float w=W(),y=838;fill(c,PANEL2,10,y,w-10,y+89,16);p.setStyle(Paint.Style.STROKE);p.setStrokeWidth(dp(1.6f));p.setColor(GOLD2);c.drawRoundRect(new RectF(dp(10),dp(y),dp(w-10),dp(y+89)),dp(16),dp(16),p);p.setStyle(Paint.Style.FILL);p.setStyle(Paint.Style.STROKE);p.setStrokeWidth(dp(2.5f));c.drawCircle(dp(39),dp(y+44),dp(19),p);p.setStyle(Paint.Style.FILL);txt(c,"☎",27,y+53,23,GOLD2,true);txt(c,"Potřebujete konzultaci?",67,y+36,12.5f,WHITE,true);txt(c,"Ozvěte se nám!",67,y+58,11.5f,MUTED,false);fill(c,GOLD2,w-130,y+18,w-22,y+71,11);center(c,"☎  Zavolat",w-76,y+51,12,Color.BLACK,true);}
        void webPanel(Canvas c){float w=W(),y=944;fill(c,PANEL,10,y,w-10,y+80,14);txt(c,"◎",24,y+47,25,GOLD2,true);txt(c,"stavbysomsi.cz",60,y+31,13,WHITE,true);txt(c,"Oficiální web • realizace • služby • kontakt",60,y+53,8.5f,MUTED,false);fill(c,Color.rgb(41,56,63),w-111,y+17,w-23,y+62,10);center(c,"OTEVŘÍT",w-67,y+45,9,GOLD2,true);}
        void contact(Canvas c){float w=W(),y=1041;fill(c,PANEL2,10,y,w-10,y+96,14);txt(c,"⌖",24,y+37,23,GOLD2,true);txt(c,"Sídlo firmy",60,y+28,9,MUTED,false);txt(c,"Horní Studenec 29",60,y+51,11,WHITE,true);txt(c,"538 43 Třemošnice",60,y+73,10,WHITE,false);line(c,MUTED,1,w/2-4,y+15,w/2-4,y+80);txt(c,"◷",w/2+12,y+37,20,GOLD2,true);txt(c,"Působíme v regionech",w/2+40,y+28,9,MUTED,false);txt(c,"Pardubický kraj",w/2+40,y+49,9.5f,WHITE,true);txt(c,"Královéhradecký kraj",w/2+40,y+67,9.5f,WHITE,true);txt(c,"Vysočina",w/2+40,y+85,9.5f,WHITE,true);}
        void drawPage(Canvas c){float w=W();fill(c,Color.rgb(8,14,18),0,0,w,72,0);txt(c,"‹",18,47,35,GOLD2,true);txt(c,section,61,45,21,WHITE,true);txt(c,"SOMSI",w-80,43,16,GOLD2,true);fill(c,PANEL,12,91,w-12,310,16);txt(c,section.toUpperCase(),28,119,11,MUTED,true);if(section.equals("Zakázky")){txt(c,"86",28,164,36,WHITE,true);txt(c,"Aktivní zakázka",116,140,14,WHITE,true);txt(c,"Novostavba – Horní Studenec",116,169,11,MUTED,false);txt(c,"Dokončení: 30. 10. 2026",116,198,11,GOLD2,true);}else if(section.equals("Fotodokumentace")){txt(c,"Realizace SOMSI",28,148,18,WHITE,true);if(hero!=null)c.drawBitmap(hero,null,new RectF(dp(28),dp(165),dp(w-28),dp(280)),p);}else if(section.equals("Stavební deník")){txt(c,"Dnešní zápis",28,153,18,WHITE,true);txt(c,"Práce pokračují podle harmonogramu.",28,184,11,MUTED,false);txt(c,"Materiál • počasí • poznámky",28,216,11,GOLD2,true);}else if(section.equals("Úkoly")){txt(c,"✓  Zkontrolovat materiál",28,154,13,WHITE,true);txt(c,"✓  Dokončit fotodokumentaci",28,190,13,WHITE,true);txt(c,"○  Připravit předání stavby",28,226,13,MUTED,true);}else if(section.equals("Docházka")){txt(c,"Přítomni dnes",28,154,17,WHITE,true);txt(c,"12 pracovníků",28,190,28,WHITE,true);txt(c,"Evidence uložená v zařízení.",28,226,10,GOLD2,true);}else if(section.equals("Materiál")){txt(c,"Cihly",28,154,14,WHITE,true);txt(c,"1 240 ks",w-105,154,12,GOLD2,true);txt(c,"Izolace",28,194,14,WHITE,true);txt(c,"84 m²",w-105,194,12,GOLD2,true);txt(c,"Cement",28,234,14,WHITE,true);txt(c,"160 pytlů",w-105,234,12,GOLD2,true);}else if(section.equals("Dokumenty")){txt(c,"Smlouvy a nabídky",28,154,15,WHITE,true);txt(c,"Rozpočty a předávací protokoly",28,186,11,MUTED,false);txt(c,"Dokumenty připravené pro další rozšíření.",28,222,10,GOLD2,true);}else if(section.equals("Adresář")){txt(c,"Petr SOMSI",28,154,15,WHITE,true);txt(c,"+420 736 771 754",28,181,11,GOLD2,true);txt(c,"Zdeněk",28,219,15,WHITE,true);txt(c,"Kontakty uložené v aplikaci",28,246,10,MUTED,false);}else if(section.equals("Chat")){List<String> ms=db.messages();int yy=151;for(String m:ms){txt(c,m,28,yy,10.5f,WHITE,false);yy+=30;if(yy>270)break;}fill(c,PANEL2,28,276,w-28,306,9);txt(c,"Napsat zprávu…",43,297,10,MUTED,false);}else{txt(c,"Sekce "+section,28,154,21,WHITE,true);txt(c,"Funkce je připravena pro práci v telefonu.",28,188,11,MUTED,false);}fill(c,PANEL2,12,337,w-12,390,14);center(c,"‹  Zpět na úvod",w/2,369,11,GOLD2,true);}
        @Override public boolean onTouchEvent(MotionEvent e){if(e.getAction()!=MotionEvent.ACTION_UP)return true;float x=e.getX()/den(),y=e.getY()/den(),w=W();if(section.equals("Domů")){if(y<80&&x<82){showMenu();return true;}if(y<80&&x>w-115){openWeb();return true;}if(y>=520&&y<832){int row=(int)((y-520)/104),col=Math.min(2,(int)(x/((w-4)/3)));int i=row*3+col;if(i>=0&&i<9){if(i==8)chat();else go(names[i]);}return true;}if(y>=838&&y<935&&x>w-150){call();return true;}if(y>=944&&y<1030){openWeb();return true;}if(y>=1041&&y<1145&&x>35&&x<300){call();return true;}}else if(y<75){go("Domů");return true;}else if(y>=337&&y<405){go("Domů");return true;}return true;}
    }

    class BottomView extends View{
        Paint p=new Paint(Paint.ANTI_ALIAS_FLAG);int selected=0;BottomView(Context c){super(c);setBackgroundColor(Color.rgb(7,13,17));setClickable(true);}float W(){return getWidth()/den();}
        void txt(Canvas c,String s,float x,float y,float z,int col,boolean b){p.setColor(col);p.setTextSize(dp(z));p.setTypeface(Typeface.create("sans",b?Typeface.BOLD:Typeface.NORMAL));p.setStyle(Paint.Style.FILL);c.drawText(s,dp(x)-p.measureText(s)/2,dp(y),p);}
        void icon(Canvas c,float x,float y,int type,int color){p.setColor(color);p.setStyle(Paint.Style.STROKE);p.setStrokeWidth(dp(2.5f));p.setStrokeCap(Paint.Cap.ROUND);float X=dp(x),Y=dp(y);if(type==0){Path q=new Path();q.moveTo(X-dp(9),Y);q.lineTo(X,Y-dp(8));q.lineTo(X+dp(9),Y);q.lineTo(X+dp(8),Y+dp(9));q.lineTo(X-dp(8),Y+dp(9));q.close();c.drawPath(q,p);}else if(type==1){c.drawRect(X-dp(9),Y-dp(6),X+dp(9),Y+dp(9),p);c.drawLine(X-dp(5),Y-dp(10),X+dp(5),Y-dp(10),p);}else if(type==2){p.setStyle(Paint.Style.FILL);c.drawCircle(X,Y,dp(27),p);p.setColor(Color.BLACK);c.drawRect(X-dp(12),Y-dp(2),X+dp(12),Y+dp(2),p);c.drawRect(X-dp(2),Y-dp(12),X+dp(2),Y+dp(12),p);}else if(type==3){c.drawOval(new RectF(X-dp(11),Y-dp(8),X+dp(11),Y+dp(7)),p);c.drawCircle(X-dp(4),Y,dp(1),p);c.drawCircle(X,Y,dp(1),p);c.drawCircle(X+dp(4),Y,dp(1),p);}else{c.drawLine(X-dp(9),Y-dp(7),X+dp(9),Y-dp(7),p);c.drawLine(X-dp(9),Y,X+dp(9),Y,p);c.drawLine(X-dp(9),Y+dp(7),X+dp(9),Y+dp(7),p);}p.setStyle(Paint.Style.FILL);p.setStrokeCap(Paint.Cap.BUTT);}
        @Override protected void onDraw(Canvas c){super.onDraw(c);float w=W();float[] xs={w*.10f,w*.30f,w*.50f,w*.70f,w*.90f};int[] types={0,1,2,3,4};String[] labels={"Domů","Zakázky","Nový záznam","Chat","Menu"};for(int i=0;i<5;i++){int col=i==selected?GOLD2:MUTED;if(i==2){p.setColor(GOLD2);p.setStyle(Paint.Style.FILL);c.drawCircle(dp(xs[i]),dp(27),dp(27),p);}icon(c,xs[i],27,types[i],i==2?Color.BLACK:col);txt(c,labels[i],xs[i],66,i==2?9:10,col,true);}p.setColor(RED);p.setStyle(Paint.Style.FILL);c.drawCircle(dp(xs[3]+14),dp(8),dp(11),p);txt(c,"3",xs[3]+14,12,8,WHITE,true);}
        @Override public boolean onTouchEvent(MotionEvent e){if(e.getAction()!=MotionEvent.ACTION_UP)return true;float x=e.getX()/den(),w=W();int i=Math.max(0,Math.min(4,(int)(x/(w/5))));selected=i;invalidate();if(i==0)go("Domů");else if(i==1)go("Zakázky");else if(i==2)newRecord();else if(i==3)chat();else showMenu();return true;}
    }
    static class DB extends SQLiteOpenHelper{
        DB(Context c){super(c,"somsi.db",null,3);}public void onCreate(SQLiteDatabase d){d.execSQL("CREATE TABLE records(id INTEGER PRIMARY KEY AUTOINCREMENT,title TEXT,detail TEXT,created INTEGER)");d.execSQL("CREATE TABLE messages(id INTEGER PRIMARY KEY AUTOINCREMENT,author TEXT,msg TEXT,created INTEGER)");d.execSQL("INSERT INTO messages(author,msg,created) VALUES('SOMSI','Vítejte v interním chatu.',strftime('%s','now'))");}public void onUpgrade(SQLiteDatabase d,int a,int b){if(a<3){try{d.execSQL("ALTER TABLE messages ADD COLUMN created INTEGER DEFAULT 0");}catch(Exception ignored){}}}void addRecord(String t,String x){ContentValues v=new ContentValues();v.put("title",t);v.put("detail",x);v.put("created",System.currentTimeMillis());getWritableDatabase().insert("records",null,v);}void addMessage(String a,String m){ContentValues v=new ContentValues();v.put("author",a);v.put("msg",m);v.put("created",System.currentTimeMillis());getWritableDatabase().insert("messages",null,v);}List<String> messages(){List<String> out=new ArrayList<>();Cursor c=getReadableDatabase().rawQuery("SELECT author,msg FROM messages ORDER BY id DESC LIMIT 6",null);while(c.moveToNext())out.add(c.getString(0)+": "+c.getString(1));c.close();return out;}
    }
}
