package cz.somsi.app;

import android.app.*;import android.os.*;import android.content.*;import android.graphics.*;import android.net.Uri;import android.provider.MediaStore;import android.view.*;import android.widget.*;

public class MainActivity extends Activity {
 static final String WEB="https://stavbysomsi.cz/"; static final String PHONE="+420736771754"; HomeView home;
 @Override public void onCreate(Bundle s){super.onCreate(s);hide();home=new HomeView(this);setContentView(home);}
 void hide(){if(Build.VERSION.SDK_INT>=30){WindowInsetsController c=getWindow().getInsetsController();if(c!=null)c.hide(WindowInsets.Type.statusBars()|WindowInsets.Type.navigationBars());}else{getWindow().setFlags(1024,1024);getWindow().getDecorView().setSystemUiVisibility(5894);}}
 void web(){try{startActivity(new Intent(Intent.ACTION_VIEW,Uri.parse(WEB)));}catch(Exception e){}}
 void call(){try{startActivity(new Intent(Intent.ACTION_DIAL,Uri.parse("tel:"+PHONE)));}catch(Exception e){}}
 void camera(){try{startActivity(new Intent(MediaStore.ACTION_IMAGE_CAPTURE));}catch(Exception e){}}
 void section(String n){if(n.equals("Fotodokumentace")){camera();return;}new AlertDialog.Builder(this).setTitle(n).setMessage("Sekce SOMSI „"+n+"“ je připravena k použití.").setPositiveButton("Zavřít",null).show();}
 void chat(){EditText e=new EditText(this);e.setHint("Napište zprávu…");new AlertDialog.Builder(this).setTitle("SOMSI Chat").setView(e).setNegativeButton("Zavřít",null).setPositiveButton("Odeslat",(d,w)->{}).show();}
 void menu(){String[] a={"Otevřít web","Zavolat","Zakázky","Chat","Adresář","Nový záznam"};new AlertDialog.Builder(this).setTitle("SOMSI").setItems(a,(d,w)->{if(w==0)web();else if(w==1)call();else if(w==3)chat();else if(w==4)section("Adresář");else if(w==5)new AlertDialog.Builder(this).setTitle("Nový záznam").setItems(new String[]{"Zakázka","Fotografie","Úkol","Docházka","Materiál","Poznámka"},(x,y)->{if(y==1)camera();}).show();else section("Zakázky");}).show();}
 class HomeView extends View{Bitmap b;Paint p=new Paint(3);float sc,l,t;HomeView(Context c){super(c);b=BitmapFactory.decodeResource(getResources(),R.drawable.realizace_hlavni);}
 protected void onDraw(Canvas c){c.drawColor(Color.rgb(5,11,15));if(b==null)return;sc=Math.min(getWidth()/(float)b.getWidth(),getHeight()/(float)b.getHeight());float w=b.getWidth()*sc,h=b.getHeight()*sc;l=(getWidth()-w)/2;t=(getHeight()-h)/2;c.drawBitmap(b,null,new RectF(l,t,l+w,t+h),p);drawOverlay(c,w,h,l,t);}
 void drawOverlay(Canvas c,float w,float h,float l,float t){float sx=w/759f,sy=h/1511f;p.setTypeface(Typeface.create("sans",Typeface.BOLD));p.setTextAlign(Paint.Align.CENTER);p.setColor(Color.WHITE);p.setTextSize(40*sx);c.drawText("SOMSI",l+w*.5f,t+h*.15f,p);p.setTextSize(18*sx);c.drawText("stavební práce",l+w*.5f,t+h*.18f,p);p.setColor(Color.rgb(244,178,36));p.setTextSize(22*sx);c.drawText("Od základu po střechu",l+w*.5f,t+h*.215f,p);String[] ns={"Zakázky","Fotodokumentace","Stavební deník","Úkoly","Docházka","Materiál","Dokumenty","Adresář","Chat"};for(int i=0;i<9;i++){int r=i/3,col=i%3;float x=l+w*(.165f+col*.335f),y=t+h*(.51f+r*.074f);p.setColor(Color.WHITE);p.setTextSize(13*sx);c.drawText(ns[i],x,y,p);}p.setColor(Color.rgb(244,178,36));p.setTextSize(18*sx);c.drawText("☎  Zavolat",l+w*.72f,t+h*.755f,p);p.setColor(Color.WHITE);p.setTextSize(14*sx);c.drawText("Domů        Zakázky       +       Chat       Menu",l+w*.5f,t+h*.965f,p);}
 boolean hit(float x,float y,float a,float b,float c,float d){return x>=a&&x<=c&&y>=b&&y<=d;}
 public boolean onTouchEvent(MotionEvent e){if(e.getAction()!=1)return true;float x=(e.getX()-l)/sc,y=(e.getY()-t)/sc;if(x<0||y<0||x>759||y>1511)return true;if(hit(x,y,0,50,100,170)){menu();return true;}if(hit(x,y,650,40,759,180)){web();return true;}String[][] n={{"Zakázky","Fotodokumentace","Stavební deník"},{"Úkoly","Docházka","Materiál"},{"Dokumenty","Adresář","Chat"}};for(int r=0;r<3;r++)for(int col=0;col<3;col++){if(hit(x,y,col*253+4,710+r*118+4,col*253+249,824+r*118)){if(n[r][col].equals("Chat"))chat();else section(n[r][col]);return true;}}if(hit(x,y,0,1050,759,1190)){call();return true;}if(hit(x,y,0,1360,759,1511)){if(x<150)return true;if(x<300)section("Zakázky");else if(x<470)menu();else if(x<620)chat();else menu();return true;}return true;}}
}